version: "3.7"

services:
  api:
    # image: shortener_api
    build: .
    container_name: shortener_api
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgres

  celery:
    # image: shortener_api
    build: .
    container_name: shortener_celery
    restart: always
    command: celery -A app.tasks worker -Q tasks -n worker@%h -l info
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortening
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
  
  redis:
    image: redis
    ports:
      - 6379:6379

  flower:  
    image: mher/flower
    restart: always
    command: celery flower --persistent=True
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8080
    ports:  
      - 8080:8080
    depends_on:
      - redis


volumes:
  postgres-data:
  pgadmin-data: